# Generated by Django 4.1.13 on 2024-07-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
            ],
        ),
    ]
