# Generated by Django 4.1.13 on 2024-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecalendar', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
