# Generated by Django 4.1.13 on 2024-07-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlecalendar', '0003_event_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlecalendar.user')),
            ],
        ),
    ]
