# Generated by Django 4.1.13 on 2024-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecalendar', '0004_googleauthrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='done',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='temp-id', max_length=255),
            preserve_default=False,
        ),
    ]
